### ISSUE TITLE
do you have new version

### ISSUE THREAD

**Issue by njsunsky** [AlexObukhoff/opc_workshop#1]
hi,my friend,thanks for your code,do you have any new version

**Comment by AlexObukhoff** [comment]
Unfortunately, I haven't been doing this project for a long time. This is the latest version that I have.

**Comment by njsunsky** [comment]
Thank you for your reply anyway. I believe you are doing more important things and I hope you are doing well.










在 2023-03-31 02:19:29，"AlexObukhoff" ***@***.***> 写道：

Closed #1 as completed.
